"""Localization helpers and UI text for English and Simplified Chinese."""

from config import OPTION_TEXT

LANGUAGE_LABELS = {
    "en": "English (US)",
    "zh": "简体中文"
}

TEXT = {
    "en": {
        "app_title": "Steel Tycoon",
        "subtitle": "Build an iron and steel empire through credit cycles, industrial rivalry, and survival.",
        "new_game": "New Game",
        "load_game": "Load Game",
        "settings": "Settings",
        "exit": "Exit",
        "new_game_setup": "New Game Setup",
        "company_name": "Company Name:",
        "scenario": "Scenario:",
        "difficulty": "Difficulty:",
        "ai_count": "AI Count:",
        "ai_strategy": "AI {index} Strategy:",
        "turn_limit": "Turn Limit:",
        "fixed_19c_note": "19th Century scenario uses six historical rivals. Only company name and difficulty can be changed.",
        "starting_cash": "Starting Cash:",
        "show_ai_stats": "Show AI statistics during the game",
        "start_game": "Start Game",
        "back": "Back",
        "saved_games_info": "Saved games in the project saves folder:",
        "load_selected_save": "Load Selected Save",
        "delete_selected_save": "Delete Selected Save",
        "no_save_selected_title": "No Save Selected",
        "no_save_selected": "Please select a save file first.",
        "loading_save": "Loading {save}...",
        "delete_save_title": "Delete Save",
        "delete_save_confirm": "Are you sure you want to delete {save}?",
        "window_resolution": "Window Resolution:",
        "language": "Language:",
        "font_scale": "Font Scale:",
        "apply_settings": "Apply Settings",
        "settings_updated": "Settings Updated",
        "settings_updated_detail": "Window size changed to {resolution}. Language set to {language}. Font scale set to {font_scale:.0f}%.",
        "no_game_state": "No game state found. Please start a new game first.",
        "back_to_main_menu": "Back to Main Menu",
        "menu": "Menu",
        "company_information": "Company Information",
        "player_actions": "Actions",
        "production_quantity": "Production Quantity:",
        "selling_price": "Selling Price:",
        "end_turn": "End Turn",
        "save_game": "Save Game",
        "save_success": "Game saved to {save}.",
        "save_failed": "Save Failed",
        "load_failed": "Load Failed",
        "no_saves_found": "No saves found.",
        "long_term_actions": "Long-term Actions:",
        "science_technology": "Science & Technology",
        "factory": "Factory",
        "contracts": "Contracts",
        "available_contracts": "Available Orders",
        "active_contracts": "Active Contracts",
        "no_available_contracts": "No open orders are available right now.",
        "no_active_contracts": "No active contracts.",
        "contract_bid_price": "Bid Unit Price:",
        "compete_contract": "Compete for Contract",
        "contract_units": "Units/Turn",
        "contract_price": "Target Price",
        "contract_duration": "Duration",
        "contract_quality": "Quality Required",
        "contract_reputation": "Reputation Required",
        "contract_holder": "Holder",
        "contract_won": "won {contract} at ${price:.2f}/unit for {duration} turns.",
        "contract_lost": "lost {contract}. Winner: {winner} at ${price:.2f}/unit.",
        "contract_fulfilled_report": "{name} delivered {delivered}/{required} units for {contract}: revenue ${revenue:.2f}, penalty ${penalty:.2f}.",
        "contract_expired_report": "{contract} has ended.",
        "factory_slots": "Factory Slots",
        "factory_type": "Type",
        "owned_factory": "Owned",
        "leased_factory": "Leased",
        "factory_expansions": "Expansions",
        "factory_rent": "Rent",
        "unassigned_workers": "Unassigned Workers",
        "worker_count": "Worker Count:",
        "production_line": "Line",
        "production_method": "Method",
        "line_active": "Active",
        "line_inactive": "Stopped",
        "assigned_workers": "Workers",
        "assign_workers": "Assign Workers",
        "add_workers": "Add Workers",
        "remove_workers": "Remove Workers",
        "upgrade_line": "Upgrade Line",
        "start_line": "Start Line",
        "stop_line": "Stop Line",
        "fire_workers": "Fire Workers",
        "build_factory": "Build Factory",
        "lease_factory": "Lease Factory",
        "expand_factory": "Expand Factory",
        "build_line_here": "Build Line Here",
        "cannot_expand_leased": "Leased factories cannot expand",
        "expansion_limit_reached": "Expansion limit reached",
        "collapse_factory": "Collapse",
        "expand_view": "Expand",
        "batch_add_workers": "Add to All Lines",
        "batch_remove_workers": "Remove from All Lines",
        "batch_upgrade_lines": "Upgrade All Lines",
        "upgrade_to_method": "Upgrade to {method} (${cost:.2f})",
        "already_best_method": "Best available method",
        "technology_tree": "Technology Tree",
        "known_technology": "Known",
        "researching_technology": "Researching ({turns} turns)",
        "locked_technology": "Locked",
        "start_research": "Start Research (${cost:.2f})",
        "buy_technology": "Negotiate Technology Purchase",
        "technology_offer": "Technology Offer:",
        "technology_sale_rejected": "{seller} refused to sell {technology}. Expected at least ${asking_price:.2f}.",
        "technology_bought": "bought {technology} from {seller} for ${cost:.2f}.",
        "technology_research_started": "started researching {technology} for ${cost:.2f}.",
        "technology_completed_report": "{name} completed research: {technology}.",
        "tech_cost": "Cost",
        "tech_turns": "Turns",
        "tech_prerequisites": "Prerequisites",
        "tech_status": "Status",
        "no_active_research": "None",
        "research_project_summary": "{technology} ({turns} turns)",
        "buy_production_line": "Buy Production Line",
        "hire_workers": "Hire Workers",
        "expand_storage": "Expand Storage",
        "marketing_campaign": "Marketing Campaign",
        "acquire_competitor": "Negotiate Acquisition",
        "acquisition_offer": "Acquisition Offer:",
        "acquisition_rejected": "{target} rejected the offer. Expected at least ${asking_price:.2f}.",
        "finance": "Finance:",
        "finance_chart": "Finance Chart",
        "chart_cash": "Cash",
        "chart_debt": "Loan / Negative Cash",
        "chart_credit_limit": "Credit Limit",
        "chart_no_data": "Not enough finance history yet.",
        "emergency_restructure": "Emergency Restructure",
        "turn_log": "Turn Log",
        "game_started": "Game started. Enter production quantity and selling price, then click End Turn.\n",
        "invalid_input_title": "Invalid Input",
        "invalid_input": "Please enter valid production and price values.\n\n{error}",
        "duplicate_strategy": "Each custom AI must use a different historical strategy.",
        "turn_error": "Turn Error",
        "game_over": "Game Over",
        "turn_header": "===== Turn {turn} Report =====\n{report}",
        "top_info": "Turn: {turn}/{max_turns} | Scenario: {scenario} | Difficulty: {difficulty} | Market Demand: {demand} | {summary}",
        "infinite_turns": "No limit",
        "market_summary": "Demand Trend: {trend:.2f} | Event: {event} (demand multiplier {multiplier:.2f}x) | Materials: {materials:.2f}x | Labor: {labor:.2f}x",
        "stable_market": "Stable Market",
        "supply_chain_shock": "Supply Chain Shock",
        "consumer_hype": "Consumer Hype",
        "new_regulation": "New Regulation",
        "market_demand_report": "Market demand this turn: {demand} units",
        "produced_report": "{name} produced {quantity} units.",
        "ai_report": "{name} ({strategy}) produced {quantity} units and set price at ${price:.2f}.",
        "ai_invested_report": "{name} invested ${amount:.2f} before production.",
        "sold_report": "{name} sold {sales} units and earned ${revenue:.2f}.",
        "profit_report": "{name}: profit ${profit:.2f}, cash ${cash:.2f}, debt ${debt:.2f}.",
        "cost_report": "Cost split: production ${production:.2f}, fixed ${fixed:.2f}, storage ${storage:.2f}, interest ${interest:.2f}.",
        "cash_flow_report": "Cash flow: revenue ${revenue:.2f}; production ${production:.2f}; wages ${wages:.2f}; maintenance ${maintenance:.2f}; rent ${rent:.2f}; storage ${storage:.2f}; interest ${interest:.2f}; profit ${profit:.2f}.",
        "bankrupt_report": "{name} has gone bankrupt because debt exceeded its credit limit.",
        "credit_crisis_report": "{name} is in a credit crisis: debt is {ratio:.1f}% of its credit limit.",
        "player_bankrupt_process": "Player company is bankrupt. Game over.",
        "game_over_bankrupt": "Game Over: Your company went bankrupt.",
        "victory_all_bankrupt": "Victory: All AI competitors went bankrupt.",
        "game_finished": "Game Finished!\n\nFinal Ranking by Company Value:\n",
        "ranking_line": "{index}. {name}: ${value:.2f}\n",
        "you_won": "\nYou won!",
        "you_lost": "\nYou lost.",
        "game_running": "Game is still running.",
        "acquired_report": "You acquired {target} for ${cost:.2f}. You gained production capacity, workers, storage, and reputation.",
        "no_acquisition_target": "No weak competitor is available for acquisition yet.",
        "player_action_prefix": "Player action: {message}",
        "production_line_log": "built a production line in {factory} for ${cost:.2f}.",
        "hire_workers_log": "hired {count} workers for ${cost:.2f}.",
        "fire_workers_log": "fired {count} workers.",
        "workers_changed_log": "changed production line workers by {delta}.",
        "batch_workers_changed_log": "changed workers by {delta} on each line in {factory}.",
        "upgrade_line_log": "upgraded a production line to {method} for ${cost:.2f}.",
        "batch_upgrade_lines_log": "upgraded {count} production lines to {method} for ${cost:.2f}.",
        "factory_built_log": "built {factory} for ${cost:.2f}.",
        "factory_leased_log": "leased {factory} for ${cost:.2f}.",
        "factory_expanded_log": "expanded {factory} for ${cost:.2f}.",
        "storage_log": "expanded storage by 250 units for ${cost:.2f}.",
        "marketing_log": "ran a marketing campaign for ${cost:.2f}.",
        "restructure_log": "emergency restructuring reduced debt by ${amount:.2f}, but damaged reputation and quality.",
        "status_company": "Company",
        "status_strategy": "Strategy",
        "status_cash": "Cash",
        "status_debt": "Loan",
        "status_credit_limit": "Credit Limit",
        "status_interest_rate": "Interest Rate",
        "status_solvency_ratio": "Solvency Ratio",
        "status_bonus": "Difficulty Bonus",
        "status_inventory": "Inventory",
        "status_production_lines": "Production Lines",
        "status_technology": "Best Production Method",
        "status_quality": "Product Quality",
        "status_known_technologies": "Technologies Known",
        "status_active_research": "Active Research",
        "status_workforce": "Workforce",
        "status_storage": "Storage Capacity",
        "status_reputation": "Reputation",
        "status_price": "Current Price",
        "status_market_share": "Market Share",
        "status_capacity": "Production Capacity",
        "status_last_production": "Last Production",
        "status_last_sales": "Last Sales",
        "status_last_demand": "Last Demand Allocation",
        "status_last_revenue": "Last Revenue",
        "status_last_cost": "Last Cost",
        "status_last_production_cost": "Production Cost",
        "status_last_fixed_cost": "Fixed Cost",
        "status_last_storage_cost": "Storage Cost",
        "status_last_interest_cost": "Interest Cost",
        "status_last_wage_cost": "Wages",
        "status_last_maintenance_cost": "Maintenance",
        "status_last_rent_cost": "Rent",
        "status_last_contract_revenue": "Contract Revenue",
        "status_last_contract_penalty": "Contract Penalty",
        "status_unit_cost": "Unit Cost",
        "status_last_profit": "Last Profit",
        "status_section_identity": "Identity",
        "status_section_finance": "Finance",
        "status_section_operations": "Operations",
        "status_section_production": "Production",
        "status_section_technology": "Technology",
        "status_section_last_turn": "Last Turn",
        "status_factories": "Factories",
        "status_effective_quality": "Effective Quality",
        "units": "units",
        "units_per_turn": "units/turn"
    },
    "zh": {
        "app_title": "钢铁大亨",
        "subtitle": "在信贷周期、产业竞争和生存压力中建立钢铁帝国。",
        "new_game": "新游戏",
        "load_game": "读取游戏",
        "settings": "设置",
        "exit": "退出",
        "new_game_setup": "新游戏设置",
        "company_name": "公司名称：",
        "scenario": "市场场景：",
        "difficulty": "难度：",
        "ai_count": "AI 数量：",
        "ai_strategy": "AI {index} 策略：",
        "turn_limit": "回合上限：",
        "fixed_19c_note": "19 世纪剧本使用六个历史对手，只能调整公司名称和难度。",
        "starting_cash": "初始现金：",
        "show_ai_stats": "游戏中显示 AI 数据",
        "start_game": "开始游戏",
        "back": "返回",
        "saved_games_info": "项目 saves 文件夹中的存档：",
        "load_selected_save": "读取选中存档",
        "delete_selected_save": "删除选中存档",
        "no_save_selected_title": "未选择存档",
        "no_save_selected": "请先选择一个存档文件。",
        "loading_save": "正在读取 {save}...",
        "delete_save_title": "删除存档",
        "delete_save_confirm": "确定要删除 {save} 吗？",
        "window_resolution": "窗口分辨率：",
        "language": "语言：",
        "font_scale": "字体缩放：",
        "apply_settings": "应用设置",
        "settings_updated": "设置已更新",
        "settings_updated_detail": "窗口大小已改为 {resolution}。语言已设为 {language}。字体缩放已设为 {font_scale:.0f}%。",
        "no_game_state": "没有找到游戏状态。请先开始新游戏。",
        "back_to_main_menu": "返回主菜单",
        "menu": "菜单",
        "company_information": "公司信息",
        "player_actions": "操作",
        "production_quantity": "生产数量：",
        "selling_price": "销售价格：",
        "end_turn": "结束回合",
        "save_game": "保存游戏",
        "save_success": "游戏已保存到 {save}。",
        "save_failed": "保存失败",
        "load_failed": "读取失败",
        "no_saves_found": "没有找到存档。",
        "long_term_actions": "长期行动：",
        "science_technology": "科学技术",
        "factory": "工厂",
        "contracts": "合同/订单",
        "available_contracts": "可争夺订单",
        "active_contracts": "执行中的合同",
        "no_available_contracts": "目前没有开放订单。",
        "no_active_contracts": "没有执行中的合同。",
        "contract_bid_price": "投标单价：",
        "compete_contract": "争夺合同",
        "contract_units": "每回合数量",
        "contract_price": "目标价格",
        "contract_duration": "持续时间",
        "contract_quality": "质量要求",
        "contract_reputation": "声誉要求",
        "contract_holder": "持有者",
        "contract_won": "赢得 {contract}，单价 ${price:.2f}，持续 {duration} 回合。",
        "contract_lost": "未赢得 {contract}。中标者：{winner}，单价 ${price:.2f}。",
        "contract_fulfilled_report": "{name} 为 {contract} 交付 {delivered}/{required} 件：收入 ${revenue:.2f}，违约罚金 ${penalty:.2f}。",
        "contract_expired_report": "{contract} 已结束。",
        "factory_slots": "厂房槽位",
        "factory_type": "类型",
        "owned_factory": "自有",
        "leased_factory": "租赁",
        "factory_expansions": "扩建次数",
        "factory_rent": "租金",
        "unassigned_workers": "未分配工人",
        "worker_count": "工人数量：",
        "production_line": "生产线",
        "production_method": "生产法",
        "line_active": "运行",
        "line_inactive": "停机",
        "assigned_workers": "工人",
        "assign_workers": "分配工人",
        "add_workers": "增加工人",
        "remove_workers": "减少工人",
        "upgrade_line": "升级生产线",
        "start_line": "启动生产线",
        "stop_line": "关停生产线",
        "fire_workers": "解雇工人",
        "build_factory": "新建厂房",
        "lease_factory": "租赁厂房",
        "expand_factory": "扩建厂房",
        "build_line_here": "在此新建生产线",
        "cannot_expand_leased": "租赁厂房不能扩建",
        "expansion_limit_reached": "已达到扩建上限",
        "collapse_factory": "折叠",
        "expand_view": "展开",
        "batch_add_workers": "全部增加工人",
        "batch_remove_workers": "全部减少工人",
        "batch_upgrade_lines": "全部升级生产线",
        "upgrade_to_method": "升级到 {method}（${cost:.2f}）",
        "already_best_method": "已是当前最佳生产法",
        "technology_tree": "科技树",
        "known_technology": "已掌握",
        "researching_technology": "研发中（{turns} 回合）",
        "locked_technology": "未解锁",
        "start_research": "开始研发（${cost:.2f}）",
        "buy_technology": "谈判购买技术",
        "technology_offer": "技术报价：",
        "technology_sale_rejected": "{seller} 拒绝出售 {technology}，至少期望 ${asking_price:.2f}。",
        "technology_bought": "以 ${cost:.2f} 从 {seller} 购买了 {technology}。",
        "technology_research_started": "花费 ${cost:.2f} 开始研发 {technology}。",
        "technology_completed_report": "{name} 完成研发：{technology}。",
        "tech_cost": "成本",
        "tech_turns": "耗时",
        "tech_prerequisites": "前置科技",
        "tech_status": "状态",
        "no_active_research": "无",
        "research_project_summary": "{technology}（{turns} 回合）",
        "buy_production_line": "购买生产线",
        "hire_workers": "雇佣工人",
        "expand_storage": "扩建仓储",
        "marketing_campaign": "营销活动",
        "acquire_competitor": "谈判收购",
        "acquisition_offer": "收购报价：",
        "acquisition_rejected": "{target} 拒绝了报价，至少期望 ${asking_price:.2f}。",
        "finance": "融资：",
        "finance_chart": "财务图表",
        "chart_cash": "现金",
        "chart_debt": "贷款/负现金",
        "chart_credit_limit": "信贷额度",
        "chart_no_data": "财务历史还不够。",
        "emergency_restructure": "紧急债务重组",
        "turn_log": "回合日志",
        "game_started": "游戏开始。输入生产数量和销售价格，然后点击结束回合。\n",
        "invalid_input_title": "输入无效",
        "invalid_input": "请输入有效的生产数量和价格。\n\n{error}",
        "duplicate_strategy": "自定义 AI 的历史策略不能重复。",
        "turn_error": "回合错误",
        "game_over": "游戏结束",
        "turn_header": "===== 第 {turn} 回合报告 =====\n{report}",
        "top_info": "回合：{turn}/{max_turns} | 场景：{scenario} | 难度：{difficulty} | 市场需求：{demand} | {summary}",
        "infinite_turns": "无限",
        "market_summary": "需求趋势：{trend:.2f} | 事件：{event}（需求倍率 {multiplier:.2f}x）| 原料：{materials:.2f}x | 劳动力：{labor:.2f}x",
        "stable_market": "市场稳定",
        "supply_chain_shock": "供应链冲击",
        "consumer_hype": "消费热潮",
        "new_regulation": "新监管政策",
        "market_demand_report": "本回合市场需求：{demand} 件",
        "produced_report": "{name} 生产了 {quantity} 件产品。",
        "ai_report": "{name}（{strategy}）生产了 {quantity} 件，并把价格设为 ${price:.2f}。",
        "ai_invested_report": "{name} 在生产前投入了 ${amount:.2f}。",
        "sold_report": "{name} 卖出 {sales} 件，收入 ${revenue:.2f}。",
        "profit_report": "{name}：利润 ${profit:.2f}，现金 ${cash:.2f}，债务 ${debt:.2f}。",
        "cost_report": "成本拆分：生产 ${production:.2f}，固定 ${fixed:.2f}，仓储 ${storage:.2f}，利息 ${interest:.2f}。",
        "cash_flow_report": "现金流：收入 ${revenue:.2f}；生产 ${production:.2f}；工资 ${wages:.2f}；维护 ${maintenance:.2f}；租金 ${rent:.2f}；仓储 ${storage:.2f}；利息 ${interest:.2f}；利润 ${profit:.2f}。",
        "bankrupt_report": "{name} 因债务超过信贷额度而破产。",
        "credit_crisis_report": "{name} 陷入信贷危机：债务已达到信贷额度的 {ratio:.1f}%。",
        "player_bankrupt_process": "玩家公司已经破产。游戏结束。",
        "game_over_bankrupt": "游戏结束：你的公司破产了。",
        "victory_all_bankrupt": "胜利：所有 AI 竞争对手都破产了。",
        "game_finished": "游戏结束！\n\n按公司价值排名：\n",
        "ranking_line": "{index}. {name}：${value:.2f}\n",
        "you_won": "\n你赢了！",
        "you_lost": "\n你输了。",
        "game_running": "游戏仍在进行。",
        "acquired_report": "你以 ${cost:.2f} 收购了 {target}。你获得了产能、工人、仓储和声誉。",
        "no_acquisition_target": "目前没有可以收购的弱势竞争对手。",
        "player_action_prefix": "玩家行动：{message}",
        "production_line_log": "花费 ${cost:.2f} 在 {factory} 新建了一条生产线。",
        "hire_workers_log": "花费 ${cost:.2f} 雇佣了 {count} 名工人。",
        "fire_workers_log": "解雇了 {count} 名工人。",
        "workers_changed_log": "生产线工人数量调整了 {delta}。",
        "batch_workers_changed_log": "{factory} 内每条生产线的工人数量调整了 {delta}。",
        "upgrade_line_log": "花费 ${cost:.2f} 将一条生产线升级为 {method}。",
        "batch_upgrade_lines_log": "花费 ${cost:.2f} 将 {count} 条生产线升级为 {method}。",
        "factory_built_log": "花费 ${cost:.2f} 新建了 {factory}。",
        "factory_leased_log": "花费 ${cost:.2f} 租赁了 {factory}。",
        "factory_expanded_log": "花费 ${cost:.2f} 扩建了 {factory}。",
        "storage_log": "花费 ${cost:.2f} 扩建了 250 单位仓储。",
        "marketing_log": "花费 ${cost:.2f} 开展了营销活动。",
        "restructure_log": "紧急重组减少了 ${amount:.2f} 债务，但损害了声誉和质量。",
        "status_company": "公司",
        "status_strategy": "策略",
        "status_cash": "现金",
        "status_debt": "贷款",
        "status_credit_limit": "信贷额度",
        "status_interest_rate": "利率",
        "status_solvency_ratio": "偿付压力",
        "status_bonus": "难度加成",
        "status_inventory": "库存",
        "status_production_lines": "生产线",
        "status_technology": "最高生产法",
        "status_quality": "产品质量",
        "status_known_technologies": "已掌握科技",
        "status_active_research": "正在研发",
        "status_workforce": "工人",
        "status_storage": "仓储容量",
        "status_reputation": "声誉",
        "status_price": "当前价格",
        "status_market_share": "市场份额",
        "status_capacity": "生产能力",
        "status_last_production": "上回合生产",
        "status_last_sales": "上回合销量",
        "status_last_demand": "上回合需求分配",
        "status_last_revenue": "上回合收入",
        "status_last_cost": "上回合成本",
        "status_last_production_cost": "生产成本",
        "status_last_fixed_cost": "固定成本",
        "status_last_storage_cost": "仓储成本",
        "status_last_interest_cost": "利息成本",
        "status_last_wage_cost": "工资",
        "status_last_maintenance_cost": "维护",
        "status_last_rent_cost": "租金",
        "status_last_contract_revenue": "合同收入",
        "status_last_contract_penalty": "合同罚金",
        "status_unit_cost": "单位成本",
        "status_last_profit": "上回合利润",
        "status_section_identity": "身份",
        "status_section_finance": "财务",
        "status_section_operations": "经营",
        "status_section_production": "生产",
        "status_section_technology": "技术",
        "status_section_last_turn": "上回合",
        "status_factories": "厂房",
        "status_effective_quality": "有效质量",
        "units": "件",
        "units_per_turn": "件/回合"
    }
}


# Looks up localized UI text and formats dynamic values.
def tr(locale, key, **kwargs):
    template = TEXT.get(locale, TEXT["en"]).get(key, TEXT["en"].get(key, key))
    return template.format(**kwargs)


# Converts internal option IDs into the active display language.
def display_option(value, language):
    return OPTION_TEXT.get(value, {}).get(language, value)


# Converts a displayed option label back into its internal ID.
def parse_option(label, language):
    for value in OPTION_TEXT:
        if display_option(value, language) == label:
            return value
    return label


# Resolves the selected language label to its language code.
def language_code_from_label(label):
    for code, language_label in LANGUAGE_LABELS.items():
        if language_label == label:
            return code
    return "en"


# Returns the project-local saves directory path.
